// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JSON.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20240312114229_start")]
    partial class start
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Ordinazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Disponibile")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Tavolo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TavoloId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TavoloId");

                    b.ToTable("Ordinazioni");
                });

            modelBuilder.Entity("Piatto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponibile")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrdinazioneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Prezzo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrdinazioneId");

                    b.ToTable("Piatti");
                });

            modelBuilder.Entity("Tavolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacita")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Disponibile")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tavoli");
                });

            modelBuilder.Entity("Ordinazione", b =>
                {
                    b.HasOne("Tavolo", "Tavolo")
                        .WithMany("Ordinazioni")
                        .HasForeignKey("TavoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tavolo");
                });

            modelBuilder.Entity("Piatto", b =>
                {
                    b.HasOne("Ordinazione", null)
                        .WithMany("Piatti")
                        .HasForeignKey("OrdinazioneId");
                });

            modelBuilder.Entity("Ordinazione", b =>
                {
                    b.Navigation("Piatti");
                });

            modelBuilder.Entity("Tavolo", b =>
                {
                    b.Navigation("Ordinazioni");
                });
#pragma warning restore 612, 618
        }
    }
}
