CREATE TABLE piatti (id INTEGER PRIMARY KEY AUTOINCREMENT, tipo TEXT,  nome TEXT,prezzo REAL);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('antipasti','Quadro d’autore con caviale', 55);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('antipasti','Gran crudo di mare: ostriche crostacei tartare e fantasia di pesce bianco',65);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('antipasti','Proposta di tre piccole portate calde',50);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('antipasti','Sandwich di triglia e scarola su gazpacho di pomodoro verde',35);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('antipasti','La Caprese secondo lo Chef',25);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('antipasti','Flan di verdure con leggera fonduta di parmigiano e tartufo di stagione',40);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('antipasti','Torcione naturale di fegato d’oca confettura di zucca al peperoncino',40);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('primi','Bavette sul pesce Pasta risottata con scampetti totanini seppiette e gamberetti biondi',35);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('primi','Fusillone al topinambur scampi e dressing alla birra',40);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('primi','Scucuzzùn mantecato ai ceci di spello calamaro scottato alla salvia e profumo di agrumi',35);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('primi','Ravioli all’ortica tartare di gambero rosso e il suo ristretto',40);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('primi','Bottoni farciti di radicchio fonduta di Scoppolato di Pedona e perle di bitter',35);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('primi','Vellutata di farro della Garfagnana e fagioli rossi di Sorana',25);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('primi','Tagliolini al filetto di pomodoro e basilico di Prà',25);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('secondi','Filetto di rombo al forno scaloppa di fegato d’oca tartufo nero e riduzione al Porto',40);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('secondi','Natura di calamaretti di sabbia in forno al profumo di Vermentino con millefoglie di verdure',45);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('secondi','Astice (o Aragosta)in crosta speziata daikon cremoso di carote e scaglie di aceto balsamico',65);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('secondi','Filetto di Fassona piemontese alla Rossini',55);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('secondi','Soffice di vitello brasato mosto cotto e  grano saraceno soffiato',35);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('secondi','Petto d’anatra cotto a bassa temperatura peschiere saltate riduzione al mirto e pavé di patate',40);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('vini','Passito di Pantelleria Ben Ryé ‘21 Donna Fugata',15);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('vini','Muffato della Sala ‘19 Antinori',20);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('vini','Moscato d’Asti “Bricco Quaglia” ‘22 La Spinetta',10);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('vini','Sauternes ‘14 Raymod-Lafon',20);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('vini','Gewurtztraminer Terminus ’22 Dramen',30);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('dolci','Tiramisù glassa al caffè e biscotto al cioccolato',15);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('dolci','La pastiera 2024',15);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('dolci','Apple Pie: tortino di pasta briseé alla mela e gelato alla crema',15);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('dolci','Semifreddo al passion fruit e spuma di Champagne',15);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('dolci','I nostri sorbetti',10);
INSERT INTO piatti (tipo, nome, prezzo) VALUES ('dolci','Selezione di formaggi italiani e esteri',20);